'use strict';
const assert=require('assert');
const e=require('./engine');
const d=require('./turn-dispatcher');
let s=e.createBranchState([2,2],['up','left']);
s=e.applySinglePlacement(s,{side:'up',tile:[2,5],to:5});
let o=e.createOpeningState();
let opts=d.turnOptions(s,o,[[5,6],[2,2],[0,0]],[[2,6]]);
assert.equal(opts.drawn,false);
assert(opts.actions.some(a=>a.type==='single'&&e.tileKey(a.tile)==='5-6'));
assert(opts.actions.some(a=>a.type==='double-sequence'&&a.numbers.join(',')==='2'));
assert(!opts.actions.some(a=>a.type==='single'&&e.tileKey(a.tile)==='2-2'));
let dbl=opts.actions.find(a=>a.type==='double-sequence'&&a.numbers.join(',')==='2');
let tr=d.applyTurn(s,o,[[5,6],[2,2],[0,0]],[[2,6]],dbl);
assert.equal(tr.passed,false);assert.equal(tr.drawn,false);assert.equal(tr.hand.length,2);assert(e.isNumberOpened(tr.openingState,2));assert.equal(tr.stock.length,1);
opts=d.turnOptions(s,e.createOpeningState(),[[0,0],[3,4]],[[5,5]]);
assert.equal(opts.drawn,true);assert.deepStrictEqual(opts.drawnTile,[5,5]);assert(opts.actions.some(a=>a.type==='double-sequence'&&a.numbers.join(',')==='5'));
dbl=opts.actions.find(a=>a.type==='double-sequence');tr=d.applyTurn(s,e.createOpeningState(),[[0,0],[3,4]],[[5,5]],dbl);assert.equal(tr.hand.length,2);assert.equal(tr.stock.length,0);assert(e.isNumberOpened(tr.openingState,5));
opts=d.turnOptions(s,e.createOpeningState(),[[0,0]],[[3,4]]);assert.equal(opts.phase,'pass');assert.equal(opts.drawn,true);tr=d.applyTurn(s,e.createOpeningState(),[[0,0]],[[3,4]]);assert.equal(tr.passed,true);assert.equal(tr.hand.length,2);
opts=d.turnOptions(s,e.createOpeningState(),[[5,6]],[]);let single=opts.actions.find(a=>a.type==='single');tr=d.applyTurn(s,e.createOpeningState(),[[5,6]],[],single);let hands=[tr.hand,[[0,1]],[[6,6]]];let out=d.roundOutcome({hands,stock:tr.stock,consecutivePasses:0,lastPlayerIndex:0,lastTurnResult:tr,players:3});assert.equal(out.kind,'finish');assert.equal(out.minus,0);
opts=d.turnOptions(s,e.createOpeningState(),[[5,5]],[]);dbl=opts.actions.find(a=>a.type==='double-sequence');tr=d.applyTurn(s,e.createOpeningState(),[[5,5]],[],dbl);hands=[tr.hand,[[0,1]],[[6,6]]];out=d.roundOutcome({hands,stock:tr.stock,consecutivePasses:0,lastPlayerIndex:0,lastTurnResult:tr,players:3});assert.equal(out.kind,'finish');assert.equal(out.minus,-10);
out=d.roundOutcome({hands:[[[0,0]],[[1,2]],[[6,6]]],stock:[],consecutivePasses:3,lastPlayerIndex:2,lastTurnResult:{passed:true,playedTiles:[]},players:3});assert.equal(out.kind,'block');assert.deepStrictEqual(out.remainders,[0,3,12]);
let amb=d.detectMixedFinishAmbiguity(s,e.createOpeningState(),[[5,6],[6,6]]);assert(amb);assert.deepStrictEqual(amb.ordinaryTile,[5,6]);assert.equal(amb.doubleSequence.length,1);
assert.equal(d.detectMixedFinishAmbiguity(s,e.createOpeningState(),[[5,6],[0,0]]),null);
console.log('qosa dispatcher invariants: OK');
