'use strict';
const assert=require('assert');
const e=require('./engine');
const r=require('./round-driver');
const first=(opts)=>opts.actions[0];
let s=e.createBranchState([2,2],['up','left']);s=e.applySinglePlacement(s,{side:'up',tile:[2,5],to:5});
let base={branchState:s,openingState:e.createOpeningState(),hands:[[[5,6]],[[0,0]],[[1,1]]],stock:[],currentPlayer:0,consecutivePasses:0,turns:0};
let out=r.runRound(base,first);assert.equal(out.outcome.kind,'finish');assert.equal(out.outcome.minus,0);
base={branchState:s,openingState:e.createOpeningState(),hands:[[[5,5]],[[0,0]],[[1,1]]],stock:[],currentPlayer:0,consecutivePasses:0,turns:0};
out=r.runRound(base,first);assert.equal(out.outcome.minus,-10);
let m=e.createBranchState([1,1],['up','left']);m=e.applySinglePlacement(m,{side:'left',tile:[1,2],to:2});
base={branchState:m,openingState:e.createOpeningState([1]),hands:[[[1,5],[5,5],[2,2]],[[0,0]],[[3,3]]],stock:[],currentPlayer:0,consecutivePasses:0,turns:0};
out=r.runRound(base,(opts)=>opts.actions.find(a=>a.type==='mixed-finish'));assert.equal(out.outcome.minus,-20);assert.equal(out.hands[0].length,0);
console.log('qosa round-driver invariants: OK');
