'use strict';
const assert=require('assert');
const e=require('./engine');
const t=require('./turn-kernel');
let s=e.createBranchState([2,2],['up','left']);
s=e.applySinglePlacement(s,{side:'up',tile:[2,5],to:5});
let turn=t.ordinaryTurnOptions(s,[[5,6],[0,0]],[[2,6]]);
assert.equal(turn.phase,'play'); assert.equal(turn.drawn,false); assert.equal(turn.stock.length,1);
turn=t.ordinaryTurnOptions(s,[[0,0],[3,4]],[[2,6]]);
assert.equal(turn.phase,'play'); assert.equal(turn.drawn,true); assert.deepStrictEqual(turn.drawnTile,[2,6]); assert.equal(turn.stock.length,0); assert(turn.legal.every(x=>x.handIndex===2));
let applied=t.applyOrdinaryTurn(s,[[0,0],[3,4]],[[2,6]],turn.legal[0]);
assert.equal(applied.passed,false); assert.equal(applied.drawn,true); assert.equal(applied.hand.length,2); assert.equal(applied.stock.length,0);
turn=t.ordinaryTurnOptions(s,[[0,0]],[[3,4]]);
assert.equal(turn.phase,'pass'); assert.equal(turn.drawn,true); assert.deepStrictEqual(turn.hand,[[0,0],[3,4]]); assert.equal(turn.stock.length,0);
applied=t.applyOrdinaryTurn(s,[[0,0]],[[3,4]]);
assert.equal(applied.passed,true); assert.equal(applied.hand.length,2);
turn=t.ordinaryTurnOptions(s,[[0,0]],[]); assert.equal(turn.phase,'pass'); assert.equal(turn.drawn,false);
assert.equal(t.nextPassCount(2,{passed:false}),0); assert.equal(t.nextPassCount(2,{passed:true}),3);
assert.equal(t.isBlocked({stock:[[1,1]],consecutivePasses:3,players:3}),false);
assert.equal(t.isBlocked({stock:[],consecutivePasses:2,players:3}),false);
assert.equal(t.isBlocked({stock:[],consecutivePasses:3,players:3}),true);
assert.deepStrictEqual(t.blockRemainders([[[6,6]],[[0,1],[2,3]],[]]),[12,6,0]);
console.log('qosa turn invariants: OK');
